version: '2'
services:
  miappjhipster-mongodb:
    image: mongo:4.0.9
    ports:
      - '28018:28018'
    command: mongos --configdb miappjhipster-mongodb-config
  miappjhipster-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  miappjhipster-mongodb-config:
    image: mongo:4.0.9
    container_name: miappjhipster-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
